### ISSUE TITLE
FEATURE REQUEST: Custom Functions

### ISSUE THREAD

**Issue by timothymarois** [denissimon/formula-parser#10]
It would be useful to have **custom functions**, I am attempting to mod this, but the parse method isn't exactly built for dynamic customization, it uses exact pre-defined string lengths. 

an example like

```php
->addFunction('min', function($value, $arg) {
    return min($value, $arg)
});
```

While this is a basic example, it would be very useful to have functions passing in the value and a single argument.

**Comment by denissimon** [comment]
Well, what you're suggesting is a good thing, Timothy, thanks. But, you know, the architecture of this library was designed 6 years ago, and, frankly, now I don’t have time for changing it (and for adding new features in general) due to work in the company. I'm always ready to consider pull requests, though.

**Comment by timothymarois** [comment]
> Well, what you're suggesting is a good thing, Timothy, thanks. But, you know, the architecture of this library was designed 6 years ago, and, frankly, now I don’t have time for changing it (and for adding new features in general) due to work in the company. I'm always ready to consider pull requests, though.

Yeah, I totally understand. I just wanted to put this here in case anyone could figure out the best way to handle this.
